---
- name: a play that runs entirely on the ansible host
  hosts: localhost
  connection: local
  tasks:
  - name: show hostname
    debug:
      msg: "{{ item }}"
    when: "'{{ item }}' == '127.0.0.1'"  
    with_inventory_hostnames: localhost  
  
